
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "../components/1-header/Header"
import Hero from "../components/2-hero/Hero"
import Contact from "../components/4-contact/Contact"
import Footer from "../components/5-footer/Footer"
import "../../public/style.css"


const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
 

};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="up" className="container">


          <Header />
          <Hero />
          <div className="divider" />



          {children}
          <div className="divider" />
          <Contact />
          <div className="divider" />
          <Footer />
        </div>


      </body>
    </html>
  );
}
